### ISSUE TITLE
Folder processing outputs black images

### ISSUE THREAD

**Issue by Egazaga** [nihui/cain-ncnn-vulkan#13]
When I use it with folders as an input, like
`cain-ncnn-vulkan.exe -v -i in -o out`
only the first batch works fine. With default settings it's 2 images, with "-j 1:4:1" it's 4. After that every next output is a black image.
Example with 4 processing threads.
![image](https://user-images.githubusercontent.com/48768054/103303123-43abca80-4a16-11eb-8153-2f009ba8bede.png)
Any ideas why this might be happening?

**Comment by Egazaga** [comment]
Checked on both Windows and Linux

**Comment by BahzBeih** [comment]
I got the same problem too.

**Comment by Egazaga** [comment]
"Fixed" by switching to RIFE. It's just better
https://github.com/hzwer/arXiv2020-RIFE
https://github.com/nihui/rife-ncnn-vulkan
![image](https://user-images.githubusercontent.com/48768054/106400760-8b68ac00-6431-11eb-8cea-3632a888ec02.png)

**Comment by Tsubajashi** [comment]
nihui, you can also reproduce it perfectly on google colab. so you might have a way to find out whats wrong :)
![image](https://user-images.githubusercontent.com/21346945/106516553-7f372a00-64d7-11eb-8ea3-ca27e0922838.png)

**Comment by BahzBeih** [comment]
> "Fixed" by switching to RIFE. It's just better
> https://github.com/hzwer/arXiv2020-RIFE
> https://github.com/nihui/rife-ncnn-vulkan
> ![image](https://user-images.githubusercontent.com/48768054/106400760-8b68ac00-6431-11eb-8cea-3632a888ec02.png)

thanks a lot, I will try this.

**Comment by Hudaldadi** [comment]
RIFE is not in general better.

I don't understand why CAIN is broken now, this can't be the solution for this project.

**Comment by n00mkrad** [comment]
This implementation is broken.

I guess we still have the option of using the original Pytorch code.

**Comment by 78Alpha** [comment]
original is missing the model file, so harder to come by a working version

**Comment by 78Alpha** [comment]
Have also done more testing. And it seems that some files work and some do not, without explanation or error. If the author can not reproduce, it may mean they need to test more files. I find it happens more on GIFs. A sample set of 5 had 2 work and the rest fail with a better success rate if converted to WEBP.

**Comment by Hudaldadi** [comment]
I solved this issue by trying different resolutions - divide able by 128.

And it needs a monitor on each gpu you want to run it.

it solved it for me on OSX and windows.

**Comment by OrloDavid** [comment]
Happens in Chainner too, Windows and Linux on the same hardware. It's something with NCNN. 

Sometimes it works fine for minute but then will start outputting all black images. Bummer cause it's a little faster on some stuff for me compared to Pytorch or ONNX with the same models. Quite a bit faster on Linux Mint with Intel Core i9 and integrated graphics. 

ONNX is close on Linux and Pytorch just blows and is usually twice as slow for me, which may be due to the CPU usage showing lower but that could also be more efficient code and the issue is with something else. 

Pytorch is the slowest on Windows as well in my case but not as much. 

My system details

```
System:
  Kernel: 5.15.0-107-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: ASUSTeK product: Zenbook UX5401ZAS_UX5401ZAS v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: UX5401ZAS v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: UX5401ZAS.311 date: 10/25/2023
Battery:
  ID-1: BAT0 charge: 52.7 Wh (99.2%) condition: 53.1/63.0 Wh (84.3%) volts: 13.0 min: 12.0
    model: ASUSTeK ASUS Battery serial: N/A status: N/A
  Device-1: hid-0018:04F3:4065.0001-battery model: ELAN9008:00 04F3:4065 serial: N/A charge: N/A
    status: N/A
CPU:
  Info: 14-core (6-mt/8-st) model: 12th Gen Intel Core i9-12900H bits: 64 type: MST AMCP
    arch: Alder Lake rev: 3 cache: L1: 1.2 MiB L2: 11.5 MiB L3: 24 MiB
  Speed (MHz): avg: 887 high: 1000 min/max: 400/4900:5000:3800 cores: 1: 898 2: 899 3: 1000
    4: 1000 5: 998 6: 1000 7: 995 8: 1000 9: 997 10: 998 11: 798 12: 873 13: 757 14: 793 15: 790
    16: 792 17: 793 18: 788 19: 794 20: 793 bogomips: 116736
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics vendor: ASUSTeK driver: i915 v: kernel ports:
    active: eDP-1 empty: DP-1,DP-2,HDMI-A-1 bus-ID: 0000:00:02.0 chip-ID: 8086:46a6
  Device-2: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo bus-ID: 3-9:6
    chip-ID: 13d3:5460
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 4608x2880 s-dpi: 120
  Monitor-1: eDP-1 model: Samsung res: 4608x2880 dpi: 388 diag: 356mm (14")
  OpenGL: renderer: Mesa Intel Graphics (ADL GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
Audio:
  Device-1: Intel Alder Lake PCH-P High Definition Audio vendor: ASUSTeK
    driver: sof-audio-pci-intel-tgl bus-ID: 0000:00:1f.3 chip-ID: 8086:51c8
  Sound Server-1: ALSA v: k5.15.0-107-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 0000:00:14.3
    chip-ID: 8086:51f0
  IF: wlo1 state: up mac: <filter>
Bluetooth:
  Device-1: Intel type: USB driver: btusb v: 0.8 bus-ID: 3-10:7 chip-ID: 8087:0033
  Report: hciconfig ID: hci0 rfk-id: 2 state: up address: <filter>
RAID:
  Hardware-1: Intel Volume Management Device NVMe RAID Controller driver: vmd v: 0.6
    bus-ID: 0000:00:0e.0 chip-ID: 8086:467f
Drives:
  Local Storage: total: 5.74 TiB used: 655.05 GiB (11.1%)
  ID-1: /dev/nvme0n1 vendor: Crucial model: CT2000T500SSD8 size: 1.82 TiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 37.9 C
  ID-2: /dev/sda type: USB vendor: Seagate model: ST3000DM 001-9YN166 size: 2.73 TiB
    serial: <filter>
  ID-3: /dev/sdb type: USB vendor: JMicron Tech model: Generic size: 238.47 GiB serial: <filter>
  ID-4: /dev/sdc type: USB model: DockCase DSWC1P size: 953.87 GiB serial: <filter>
  ID-5: /dev/sde type: USB vendor: Generic model: MassStorageClass size: 28.86 GiB
    serial: <filter>
Partition:
  ID-1: / size: 233.18 GiB used: 84.85 GiB (36.4%) fs: ext4 dev: /dev/sdb2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sdb1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 1.1 GiB (55.1%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 55.0 C mobo: N/A
  Fan Speeds (RPM): cpu: 3400
Repos:
  Packages: 3780 apt: 3759 flatpak: 21
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/lunarg-vulkan-1.3.283-focal.list
    1: deb [signed-by=/usr/share/keyrings/lunarg-archive-keyring.gpg] https: //packages.lunarg.com/vulkan/1.3.283 focal main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/winehq-bullseye.sources
    1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/debian bullseye main
Info:
  Processes: 450 Uptime: 2h 50m Memory: 31.03 GiB used: 5.69 GiB (18.3%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

```

**Comment by OrloDavid** [comment]
I manually set my tile sizes to 256 on the upscalers in Channner and it stopped the black output. I hope this helps and can by applied in some way here.
